version: '3.2'

services:
  database:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres